---
- name: Update apt repositories
  apt:
    update_cache: yes
  become: yes

- name: Install AWS CLI
  apt:
    name: awscli
    state: present
  become: yes

- name: Ensure AWS credentials directory exists
  file:
    path: ~/.aws
    state: directory

- name: Set AWS credentials in configuration file
  template:
    src: credentials
    dest: ~/.aws/credentials

- name: Set AWS config in config file
  template:
    src: config
    dest: ~/.aws/config
  vars:
    region: "{{ region }}"
