all:
  hosts:
    bastion_host:
      ansible_host: "{{ bastion_host }}"
      ansible_user: "{{ ansible_user }}"
  children:
    mysql_servers:
      hosts:
        master:
          ansible_host: "{{ mysql_master_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ bastion_host }}"'
        slave:
          ansible_host: "{{ mysql_slave_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_user }}@{{ bastion_host }}"'
