name: Provisioning AWS Infrastructure

on:
  push:
    paths:
      - "Terraform/**"
    branches:
      - main
  workflow_dispatch:

env:
  REGION: us-east-1

jobs:
  provision_infra:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config=backend.conf
        working-directory: Terraform

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: Terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: Terraform

      - name: Terraform Output
        run: terraform output
        working-directory: Terraform
